name: Build Electron App - gmFactures

on:
  push:
    tags:
      - 'v*' # Se déclenche lors du push d'un tag (ex: v1.0.0)

# Permissions globales pour permettre la création de la Release
permissions:
  contents: write

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Construction pour les 3 systèmes en parallèle
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm' # Optimise le temps de build en mettant le cache en mémoire

      - name: Install dependencies
        run: npm install

      - name: Build frontend (Vite)
        run: npm run build

      - name: Build & Release Electron App
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # Ici, on utilise le jeton automatique fourni par GitHub
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Force la publication sur GitHub Releases
          release: true
          args: "--publish always"
        env:
          # Correction : on utilise GITHUB_TOKEN (le secret intégré)
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}